# lib-bridge-js framework defaults
# Consumer apps should provide their own default-config.yml with partner-specific values.

# Server
server:
  port: 7432
  host: '0.0.0.0'

# Clustering
start:
  # if numProcesses=0 launch 1 process per CPU
  # if numProcesses>0 launch exactly numProcess processes
  # if numProcesses<0 launch max(numCPU + numProcess, 1) process(es)
  numProcesses: 0

# Logging
logs:
  console:
    active: true
    level: info
    format:
      color: true
      time: true
      aligned: true
  file:
    active: true
    path: application.log

# Storage
storage:
  files:
    directory: ./storage
