# sample localConfig
# copied by script/setup.ch
# 
# Add custom data here 
# used whend launched with `npm run start:prod``
server:
  host: '127.0.0.1'  # Only allow connection from localhost

# The url exposed on the internet (ex via reverse proxy)
baseURL: https://your.site

# The apiEndpoint to control your bridge account
bridgeApiEndPoint: OVERRIDE_ME

partnerAuthToken: OVERRIDE_ME # The token used to authenticate the partner backend

partnerURLs:
  webhookOnboard: 
    url: https://TO_BE_SET # Call partner backend on sucess or failure of auth process
    method: 'GET' # You may set it to POST (response infos will be sent as queryParam or JSON post )
    headers: 
      secret: 'YOUR_SECRET' # Add Headers you want to send alongisde the response
  defaultRedirectOnError: https://TO_BE_SET # A default redirect url in case of error need to be set
  
service: 
  serviceInfoURL: https://demo.datasafe.dev/reg/service/info
  appId: bridge-partner # The id of your app
  bridgeAccountMainStreamId: bridge # The root stream on the partner's bridge account
  userPermissionRequest:
    - streamId: partner-stream
      level: manage
      defaultName: Partner
  consentMessage: Connect HDS with Partner. -- to be detailed -- 